# Generated by Django 3.2.2 on 2021-05-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_post_cloudinary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cloudinary_image',
        ),
    ]
